### ISSUE TITLE
How to make the navbar a fixed width and always onebar?

### ISSUE THREAD

**Issue by ooiiredq** [Bali10050/FirefoxCSS#15]
Perfect css template, but help me with these:

How to make the navbar a fixed width for any screen sizes
How to remove the ability to roll the navbar down when the window is minimized (I need a one line layout for all screen sizes)

Didn't get what to change in media queries

**Comment by Bali10050** [comment]
You first need to remove these lines:
```
@media screen and (min-width:850px) and (max-width:1324px)    /*  Both the tabs space and the navbar will grow  */
{#nav-bar{margin-top: calc(var(--TabsHeight) * -1px - var(--TabsBorder) * 1px) !important; height: calc(var(--TabsHeight) * 1px + var(--TabsBorder) * 1px)} #TabsToolbar{margin-left: calc(var(--NavbarWidth) * 1vw) !important} #nav-bar{margin-right: calc(100vw - calc(var(--NavbarWidth) * 1vw)) !important; vertical-align: center !important} #urlbar-container{min-width: 0px !important;  flex: auto !important} toolbarspring{display: none !important} #TabsToolbar, #nav-bar{transition: margin-top .25s !important}}

@media screen and (max-width:849px)    /*  The window is not enough wide for a one line layout  */
{#nav-bar{padding: 0 5px 0 5px!important; height: calc(var(--NavbarHeightSmall) * 1px) !important} toolbarspring{display: none !important;} #TabsToolbar, #nav-bar{transition: margin-top .25s !important}}
#nav-bar, #PersonalToolbar{background-color: #0000 !important;background-image: none !important; box-shadow: none !important} #nav-bar{margin-left: 3px; border-top: none !important} .tab-background, .tab-stack { min-height: calc(var(--TabsHeight) * 1px) !important}
```

then, you need to edit this:
```
@media screen and (min-width:1325px)    /*  Only the tabs space will grow from here  */
{#nav-bar{margin-top: calc(var(--TabsHeight) * -1px - var(--TabsBorder) * 1px)!important; height: calc(var(--TabsHeight) * 1px + var(--TabsBorder) * 1px)} #TabsToolbar{margin-left: calc(1325px / 100 * var(--NavbarWidth)) !important} #nav-bar{margin-right: calc(100vw - calc(1325px / 100 * var(--NavbarWidth))) !important; vertical-align: center !important} #urlbar-container{min-width: 0px !important;  flex: auto !important} toolbarspring{display: none !important}}
```

into this:
```
#nav-bar{margin-top: calc(var(--TabsHeight) * -1px - var(--TabsBorder) * 1px)!important; height: calc(var(--TabsHeight) * 1px + var(--TabsBorder) * 1px)} #TabsToolbar{margin-left: calc(1325px / 100 * var(--NavbarWidth)) !important} #nav-bar{margin-right: calc(100vw - calc(1325px / 100 * var(--NavbarWidth))) !important; vertical-align: center !important} #urlbar-container{min-width: 0px !important;  flex: auto !important} toolbarspring{display: none !important}
```

Also, I don't recommend doing this, because the only thing it will achieve is that some buttons will start overlapping, some will get cut off by the side of the window, and using it will become a very bad experience in smaller window sizes. The only way to combat this would be to set bigger minimum size, but I don't think that's a solution, that's the reason I have written my own code for everything and didn't just fork cascade or some other oneliner theme at the time

**Comment by ooiiredq** [comment]
<img width="1680" alt="" src="https://github.com/user-attachments/assets/5bbf2f91-d128-4c02-83a5-28d327cfbb1e">
works perfect but urlbar now changed color, is there is a way to change it back to the color of tabs?

**Comment by Bali10050** [comment]
The area that has a lighter colored on the left should be the `#nav-bar`, but usually when you want to change the navbar's color, you change `#nav-bar-customization-target`, because less rules need to be rewritten then, but that doesn't have an effect on `#PanelUI-button`, so you also need to change the color of that. Also, there's a little gap between the edge of the window and every element that I just said, and nothing that only affects that part of the screen next to those elements or bellow them. Based on the screenshot you sent, I'm guessing you use macos, or you have custom gtk theme and you use a custom font with stem darkening, and I'm guessing that your firefox has some elements different than mine. If you can't find anything with the selectors that I guessed, you need to tell me what os you have, what gtk-theme you use, and you need to send me the edited css, if you want help

**Comment by ooiiredq** [comment]
fixed by simple change of a firefox theme in a firefox store
thank you
