### ISSUE TITLE
Duplicate, overlapping window controls

### ISSUE THREAD

**Issue by Terrance** [Bali10050/FirefoxCSS#19]
I've just tried setting up the `alt` @ de6efff theme on Windows with Firefox Developer Edition 133.0b5, but the minimize/restore/close buttons seem to be duplicated and obscure buttons on the right end of the toolbar.

With vertical tabs enabled:

![Vertical tabs enabled](https://github.com/user-attachments/assets/2f72bf47-c1cb-43e9-9495-a60dbdf24917)

With vertical tabs disabled (not sure if that's expected to work with this theme or not):

![Vertical tabs disabled](https://github.com/user-attachments/assets/9ebcc7e8-b0f9-4f6d-aec5-05b70176a663)

This is after using _Customize Toolbar_ > _Reset Defaults_, so hopefully no unexpected buttons in the way.

I've tried both with and without `user.js`, and have the three manual config options set as described in the readme.

**Comment by Bali10050** [comment]
I don't know why they keep changing those buttons, every two months, they change something about them, and I need to adjust the css to it. I feel like half of that sweet $500M google money goes into mixing up those buttons' properties in new ways, instead of adding all the new and interesting features that other browsers have. Anyways, 77610fd should fix the problem, sorry for the issue. Also, if your interested in horizontal tabs, I recommend checking out the [main branch](https://github.com/Bali10050/FirefoxCSS)

**Comment by Terrance** [comment]
Can confirm it's all lined up now, thanks!  (I'm in for vertical tabs, was just checking if it was expecting horizontal there and hadn't realised `main` was the horizontal version 🙃)
